services:
  backend:
    # image: backend-mysql
    build: ./backend/dockerfile/
    container_name: express-container
    hostname: express-server
    tty: true
    ports:
      - 3001:3001
    working_dir: /app
    depends_on:
      - mysql
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=3001 # コンテナ内でのポート番号
    volumes:
      - ./backend:/app
    networks:
      - mysql-prac-network

  frontend:
    # image: next-mysql
    build: ./frontend/dockerfile/
    container_name: next-container
    hostname: react-server
    tty: true
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - backend
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=3000 # コンテナ内でのポート番号
    volumes:
      - ./frontend:/app
    networks:
      - mysql-prac-network

  mysql:
    image: mysql:latest
    container_name: mysql
    # restart: always
    ports:
      - 3306:3306
    volumes:
      # DB データ永続化
      - mysql-prac:/var/lib/mysql
      # DB 文字化け対策
      - ./mysql/conf:/etc/mysql/conf.d
      # DB 初期設定
      - ./mysql/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mysql-prac-network

volumes:
  mysql-prac:

networks:
  mysql-prac-network:
    driver: bridge
