services:
  app:
    image: express-mysql
    container_name: express
    build: ./
    tty: true
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - mysql
    volumes:
      - ./:/app
    networks:
      - mysql-prac-network

  mysql:
    image: mysql:latest
    container_name: mysql
    # restart: always
    ports:
      - 3306:3306
    volumes:
      # DB 文字化け対策
      - ./mysql/conf:/etc/mysql/conf.d
      # DB 初期設定
      - ./mysql/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mysql-prac-network

volumes:
  mysql-prac:

networks:
  mysql-prac-network:
    driver: bridge
